SELECT U.USER_ID, U.NICKNAME, concat(U.CITY, ' ', U.STREET_ADDRESS1, ' ', U.STREET_ADDRESS2) AS 전체주소,
CONCAT(LEFT(u.TLNO, 3), '-', MID(u.TLNO, 4, 4), '-', RIGHT(u.TLNO, 4)) AS 전화번호 
FROM USED_GOODS_USER U
JOIN USED_GOODS_BOARD B
ON B.WRITER_ID = U.USER_ID 
GROUP BY (U.USER_ID)
HAVING count(*) >= 3
ORDER BY U.USER_ID DESC
